CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid UUID NOT NULL DEFAULT gen_random_uuid(),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    nickname VARCHAR(50),
    email VARCHAR(255),
    phone_number VARCHAR(30),
    gender VARCHAR(20),
    birth_year INTEGER,
    is_profile_completed BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ux_users_user_uuid UNIQUE (user_uuid),
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DORMANT', 'WITHDRAWN', 'BANNED')),
    CONSTRAINT chk_users_gender CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'OTHER', 'UNKNOWN')),
    CONSTRAINT chk_users_birth_year CHECK (birth_year IS NULL OR birth_year BETWEEN 1900 AND 2100)
);

CREATE TABLE user_auth_providers (
    provider_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    provider_type VARCHAR(30) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    provider_email VARCHAR(255),
    connected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_authenticated_at TIMESTAMPTZ,
    CONSTRAINT ux_auth_provider_identity UNIQUE (provider_type, provider_user_id),
    CONSTRAINT ux_auth_provider_user_type UNIQUE (user_id, provider_type),
    CONSTRAINT chk_auth_provider_type CHECK (provider_type IN ('APPLE', 'GOOGLE', 'KAKAO', 'NAVER'))
);

CREATE TABLE refresh_tokens (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash VARCHAR(255) NOT NULL,
    device_id VARCHAR(120),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_refresh_tokens_hash UNIQUE (token_hash)
);

CREATE TABLE user_devices (
    user_device_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    device_id VARCHAR(120) NOT NULL,
    device_os VARCHAR(30) NOT NULL,
    app_version VARCHAR(40),
    push_token VARCHAR(255),
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_user_devices_user_device UNIQUE (user_id, device_id),
    CONSTRAINT chk_user_devices_os CHECK (device_os IN ('IOS', 'ANDROID', 'WEB', 'UNKNOWN'))
);

CREATE TABLE user_terms_agreements (
    agreement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    terms_type VARCHAR(50) NOT NULL,
    terms_version VARCHAR(50) NOT NULL,
    is_agreed BOOLEAN NOT NULL,
    agreed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_user_terms_agreements UNIQUE (user_id, terms_type, terms_version)
);

CREATE TABLE user_profiles (
    user_id BIGINT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
    height_cm SMALLINT,
    job_title VARCHAR(100),
    education_level VARCHAR(50),
    mbti VARCHAR(10),
    introduction TEXT,
    region_code VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_user_profiles_height CHECK (height_cm IS NULL OR height_cm BETWEEN 100 AND 250)
);

CREATE TABLE user_profile_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    image_order SMALLINT NOT NULL DEFAULT 0,
    is_main BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_user_profile_images_order UNIQUE (user_id, image_order),
    CONSTRAINT chk_user_profile_images_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED'))
);

CREATE UNIQUE INDEX ux_user_profile_images_main
    ON user_profile_images(user_id)
    WHERE is_main;

CREATE TABLE user_preferences (
    user_id BIGINT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
    preferred_gender VARCHAR(20),
    preferred_age_min SMALLINT,
    preferred_age_max SMALLINT,
    preferred_region_code VARCHAR(50),
    allow_random_call BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_user_preferences_gender CHECK (preferred_gender IS NULL OR preferred_gender IN ('MALE', 'FEMALE', 'ANY')),
    CONSTRAINT chk_user_preferences_age CHECK (
        preferred_age_min IS NULL
        OR preferred_age_max IS NULL
        OR preferred_age_min <= preferred_age_max
    )
);

CREATE TABLE recommendation_exposure_history (
    exposure_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    target_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    surface_type VARCHAR(50) NOT NULL DEFAULT 'RECOMMENDATION',
    exposed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_recommendation_exposure_self CHECK (user_id <> target_user_id)
);

CREATE TABLE user_reactions (
    reaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    to_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    reaction_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_user_reactions_pair UNIQUE (from_user_id, to_user_id),
    CONSTRAINT chk_user_reactions_type CHECK (reaction_type IN ('LIKE', 'PASS')),
    CONSTRAINT chk_user_reactions_self CHECK (from_user_id <> to_user_id)
);

CREATE TABLE matches (
    match_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    user2_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    match_source VARCHAR(50) NOT NULL DEFAULT 'RECOMMENDATION',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    matched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_matches_pair UNIQUE (user1_id, user2_id),
    CONSTRAINT chk_matches_users CHECK (user1_id < user2_id),
    CONSTRAINT chk_matches_status CHECK (status IN ('ACTIVE', 'ENDED', 'BLOCKED'))
);

CREATE TABLE user_blocks (
    block_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    blocked_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_user_blocks_pair UNIQUE (blocker_id, blocked_user_id),
    CONSTRAINT chk_user_blocks_self CHECK (blocker_id <> blocked_user_id)
);

CREATE TABLE user_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    target_user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT chk_user_reports_self CHECK (reporter_id <> target_user_id),
    CONSTRAINT chk_user_reports_status CHECK (status IN ('RECEIVED', 'IN_REVIEW', 'RESOLVED', 'REJECTED'))
);

CREATE TABLE activity_log (
    activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    action_type VARCHAR(60) NOT NULL,
    target_type VARCHAR(60),
    target_id BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_rooms (
    room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES matches(match_id) ON DELETE CASCADE,
    room_type VARCHAR(30) NOT NULL DEFAULT 'MATCH',
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMPTZ,
    CONSTRAINT ux_chat_rooms_match UNIQUE (match_id),
    CONSTRAINT chk_chat_rooms_type CHECK (room_type IN ('MATCH')),
    CONSTRAINT chk_chat_rooms_status CHECK (status IN ('ACTIVE', 'CLOSED', 'BLOCKED'))
);

CREATE TABLE chat_room_members (
    room_id BIGINT NOT NULL REFERENCES chat_rooms(room_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,
    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE chat_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES chat_rooms(room_id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    message_type VARCHAR(30) NOT NULL DEFAULT 'TEXT',
    content TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'SENT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    delivered_at TIMESTAMPTZ,
    CONSTRAINT chk_chat_messages_type CHECK (message_type IN ('TEXT', 'IMAGE', 'SYSTEM')),
    CONSTRAINT chk_chat_messages_status CHECK (status IN ('SENT', 'DELIVERED', 'READ'))
);

CREATE TABLE chat_read_status (
    room_id BIGINT NOT NULL REFERENCES chat_rooms(room_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    last_read_message_id BIGINT REFERENCES chat_messages(message_id) ON DELETE SET NULL,
    read_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE chat_message_reports (
    message_report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES chat_messages(message_id) ON DELETE CASCADE,
    reporter_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT chk_chat_message_reports_status CHECK (status IN ('RECEIVED', 'IN_REVIEW', 'RESOLVED', 'REJECTED'))
);

CREATE TABLE call_user_states (
    user_id BIGINT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
    call_status VARCHAR(30) NOT NULL DEFAULT 'OFFLINE',
    last_heartbeat_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_call_user_states_status CHECK (call_status IN ('ONLINE', 'OFFLINE', 'CALL_WAITING', 'CALLING'))
);

CREATE TABLE call_queue_tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    queue_type VARCHAR(80) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'WAITING',
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    canceled_at TIMESTAMPTZ,
    matched_at TIMESTAMPTZ,
    CONSTRAINT chk_call_queue_tickets_status CHECK (status IN ('WAITING', 'MATCHED', 'CANCELED', 'EXPIRED'))
);

CREATE TABLE call_sessions (
    call_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caller_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    callee_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    match_type VARCHAR(50) NOT NULL DEFAULT 'RANDOM',
    status VARCHAR(30) NOT NULL DEFAULT 'CONNECTING',
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    failure_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_call_sessions_users CHECK (caller_id <> callee_id),
    CONSTRAINT chk_call_sessions_status CHECK (status IN ('CONNECTING', 'ACTIVE', 'ENDED', 'FAILED', 'CANCELED'))
);

CREATE TABLE call_session_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_id BIGINT NOT NULL REFERENCES call_sessions(call_id) ON DELETE CASCADE,
    event_type VARCHAR(50) NOT NULL,
    event_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason TEXT
);

CREATE TABLE coin_products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(80) NOT NULL,
    store VARCHAR(30) NOT NULL,
    store_product_id VARCHAR(120) NOT NULL,
    product_type VARCHAR(30) NOT NULL DEFAULT 'COIN',
    coin_amount INTEGER NOT NULL,
    bonus_coin_amount INTEGER NOT NULL DEFAULT 0,
    price_amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'KRW',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_coin_products_code UNIQUE (product_code),
    CONSTRAINT ux_coin_products_store_product UNIQUE (store, store_product_id),
    CONSTRAINT chk_coin_products_store CHECK (store IN ('APPLE_APP_STORE', 'GOOGLE_PLAY')),
    CONSTRAINT chk_coin_products_amount CHECK (coin_amount > 0 AND bonus_coin_amount >= 0),
    CONSTRAINT chk_coin_products_price CHECK (price_amount >= 0)
);

CREATE TABLE payment_orders (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES coin_products(product_id),
    store VARCHAR(30) NOT NULL,
    purchase_token VARCHAR(255) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'KRW',
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_payment_orders_purchase UNIQUE (store, purchase_token),
    CONSTRAINT chk_payment_orders_status CHECK (status IN ('PENDING', 'APPROVED', 'FAILED', 'CANCELED', 'REFUNDED')),
    CONSTRAINT chk_payment_orders_store CHECK (store IN ('APPLE_APP_STORE', 'GOOGLE_PLAY')),
    CONSTRAINT chk_payment_orders_amount CHECK (amount >= 0)
);

CREATE TABLE payment_receipts (
    receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payment_orders(payment_id) ON DELETE CASCADE,
    receipt_hash VARCHAR(255) NOT NULL,
    raw_reference TEXT,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_payment_receipts_payment UNIQUE (payment_id),
    CONSTRAINT ux_payment_receipts_hash UNIQUE (receipt_hash)
);

CREATE TABLE coin_wallets (
    wallet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    balance INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_coin_wallets_user UNIQUE (user_id),
    CONSTRAINT chk_coin_wallets_balance CHECK (balance >= 0)
);

CREATE TABLE coin_ledger (
    ledger_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL REFERENCES coin_wallets(wallet_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    delta INTEGER NOT NULL,
    balance_after INTEGER NOT NULL,
    reason VARCHAR(30) NOT NULL,
    ref_type VARCHAR(50),
    ref_id BIGINT,
    idempotency_key VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_coin_ledger_idempotency UNIQUE (idempotency_key),
    CONSTRAINT chk_coin_ledger_delta CHECK (delta <> 0),
    CONSTRAINT chk_coin_ledger_balance_after CHECK (balance_after >= 0),
    CONSTRAINT chk_coin_ledger_reason CHECK (reason IN ('CHARGE', 'USE', 'REFUND', 'ADJUST', 'RESERVE', 'RELEASE'))
);

CREATE TABLE coin_usage_reservations (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    wallet_id BIGINT NOT NULL REFERENCES coin_wallets(wallet_id) ON DELETE CASCADE,
    feature_type VARCHAR(50) NOT NULL,
    amount INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RESERVED',
    ref_type VARCHAR(50),
    ref_id BIGINT,
    expires_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_coin_usage_reservations_amount CHECK (amount > 0),
    CONSTRAINT chk_coin_usage_reservations_status CHECK (status IN ('RESERVED', 'COMPLETED', 'RELEASED'))
);

CREATE TABLE refund_requests (
    refund_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payment_orders(payment_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    status VARCHAR(30) NOT NULL DEFAULT 'REQUESTED',
    reason TEXT,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    CONSTRAINT chk_refund_requests_status CHECK (status IN ('REQUESTED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE community_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    slug VARCHAR(80) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_community_categories_slug UNIQUE (slug)
);

CREATE TABLE community_posts (
    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES community_categories(category_id),
    author_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    view_count INTEGER NOT NULL DEFAULT 0,
    comment_count INTEGER NOT NULL DEFAULT 0,
    like_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_community_posts_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED')),
    CONSTRAINT chk_community_posts_counts CHECK (view_count >= 0 AND comment_count >= 0 AND like_count >= 0)
);

CREATE TABLE community_post_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES community_posts(post_id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    image_order SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_community_post_images_order UNIQUE (post_id, image_order)
);

CREATE TABLE community_comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES community_posts(post_id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    parent_comment_id BIGINT REFERENCES community_comments(comment_id) ON DELETE SET NULL,
    body TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_community_comments_status CHECK (status IN ('ACTIVE', 'HIDDEN', 'DELETED'))
);

CREATE TABLE community_post_likes (
    post_id BIGINT NOT NULL REFERENCES community_posts(post_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (post_id, user_id)
);

CREATE TABLE community_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT chk_community_reports_target CHECK (target_type IN ('POST', 'COMMENT')),
    CONSTRAINT chk_community_reports_status CHECK (status IN ('RECEIVED', 'IN_REVIEW', 'RESOLVED', 'REJECTED'))
);

CREATE TABLE community_hidden_items (
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT NOT NULL,
    hidden_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, target_type, target_id),
    CONSTRAINT chk_community_hidden_items_target CHECK (target_type IN ('POST', 'COMMENT'))
);

CREATE TABLE admin_roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL,
    role_name VARCHAR(100) NOT NULL,
    permissions JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_admin_roles_code UNIQUE (role_code)
);

CREATE TABLE admin_users (
    admin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT REFERENCES admin_roles(role_id),
    login_id VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_admin_users_login_id UNIQUE (login_id),
    CONSTRAINT chk_admin_users_status CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

CREATE TABLE moderation_cases (
    case_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_type VARCHAR(50) NOT NULL,
    target_user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    target_content_type VARCHAR(30),
    target_content_id BIGINT,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    assigned_admin_id BIGINT REFERENCES admin_users(admin_id) ON DELETE SET NULL,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT chk_moderation_cases_status CHECK (status IN ('OPEN', 'IN_REVIEW', 'RESOLVED')),
    CONSTRAINT chk_moderation_cases_content_type CHECK (
        target_content_type IS NULL
        OR target_content_type IN ('USER', 'POST', 'COMMENT', 'MESSAGE', 'CALL', 'PAYMENT')
    )
);

CREATE TABLE moderation_case_items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id BIGINT NOT NULL REFERENCES moderation_cases(case_id) ON DELETE CASCADE,
    source_type VARCHAR(50) NOT NULL,
    source_id BIGINT,
    snapshot_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_sanctions (
    sanction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    sanction_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    reason TEXT,
    start_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_at TIMESTAMPTZ,
    created_by_admin_id BIGINT REFERENCES admin_users(admin_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_user_sanctions_type CHECK (sanction_type IN ('WARN', 'SUSPEND', 'BAN')),
    CONSTRAINT chk_user_sanctions_status CHECK (status IN ('ACTIVE', 'ENDED'))
);

CREATE TABLE admin_action_logs (
    action_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES admin_users(admin_id) ON DELETE SET NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id BIGINT,
    action_type VARCHAR(50) NOT NULL,
    reason TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_admin_action_logs_action CHECK (action_type IN ('WARN', 'HIDE', 'SUSPEND', 'BAN', 'REFUND_REVIEW', 'RESTORE'))
);

CREATE TABLE content_moderation_logs (
    content_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(30) NOT NULL,
    content_id BIGINT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    admin_id BIGINT REFERENCES admin_users(admin_id) ON DELETE SET NULL,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_content_moderation_logs_content CHECK (content_type IN ('POST', 'COMMENT', 'MESSAGE')),
    CONSTRAINT chk_content_moderation_logs_action CHECK (action_type IN ('HIDE', 'RESTORE', 'DELETE'))
);

CREATE TABLE payment_review_logs (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payment_orders(payment_id) ON DELETE CASCADE,
    review_type VARCHAR(50) NOT NULL,
    result VARCHAR(50) NOT NULL,
    admin_id BIGINT REFERENCES admin_users(admin_id) ON DELETE SET NULL,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ops_dashboard_snapshots (
    snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_code VARCHAR(80) NOT NULL,
    metric_value NUMERIC(20, 4) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE service_notices (
    notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id BIGINT REFERENCES admin_users(admin_id) ON DELETE SET NULL,
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_service_notices_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'HIDDEN'))
);

CREATE TABLE system_audit_logs (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type VARCHAR(30) NOT NULL,
    actor_id BIGINT,
    event_type VARCHAR(80) NOT NULL,
    target_type VARCHAR(50),
    target_id BIGINT,
    ip_address INET,
    user_agent TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_users_status ON users(status);
CREATE INDEX ix_users_email ON users(email);
CREATE INDEX ix_user_auth_providers_user_id ON user_auth_providers(user_id);
CREATE INDEX ix_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX ix_user_devices_user_id ON user_devices(user_id);
CREATE INDEX ix_recommendation_exposure_user ON recommendation_exposure_history(user_id, exposed_at DESC);
CREATE INDEX ix_recommendation_exposure_target ON recommendation_exposure_history(target_user_id);
CREATE INDEX ix_user_reactions_to_user ON user_reactions(to_user_id, reaction_type);
CREATE INDEX ix_matches_user1_status ON matches(user1_id, status);
CREATE INDEX ix_matches_user2_status ON matches(user2_id, status);
CREATE INDEX ix_user_blocks_blocked ON user_blocks(blocked_user_id);
CREATE INDEX ix_user_reports_target_status ON user_reports(target_user_id, status);
CREATE INDEX ix_activity_log_user_created ON activity_log(user_id, created_at DESC);
CREATE INDEX ix_chat_room_members_user ON chat_room_members(user_id);
CREATE INDEX ix_chat_messages_room_created ON chat_messages(room_id, created_at DESC);
CREATE INDEX ix_chat_read_status_user ON chat_read_status(user_id);
CREATE INDEX ix_call_queue_tickets_status ON call_queue_tickets(status, requested_at);
CREATE INDEX ix_call_sessions_caller ON call_sessions(caller_id, created_at DESC);
CREATE INDEX ix_call_sessions_callee ON call_sessions(callee_id, created_at DESC);
CREATE INDEX ix_call_session_events_call ON call_session_events(call_id, event_at);
CREATE INDEX ix_payment_orders_user_status ON payment_orders(user_id, status);
CREATE INDEX ix_payment_orders_product ON payment_orders(product_id);
CREATE INDEX ix_coin_wallets_user ON coin_wallets(user_id);
CREATE INDEX ix_coin_ledger_wallet_created ON coin_ledger(wallet_id, created_at DESC);
CREATE INDEX ix_coin_ledger_user_created ON coin_ledger(user_id, created_at DESC);
CREATE INDEX ix_coin_usage_reservations_user_status ON coin_usage_reservations(user_id, status);
CREATE INDEX ix_refund_requests_payment ON refund_requests(payment_id);
CREATE INDEX ix_community_posts_category_status ON community_posts(category_id, status, created_at DESC);
CREATE INDEX ix_community_posts_author ON community_posts(author_id, created_at DESC);
CREATE INDEX ix_community_comments_post_created ON community_comments(post_id, created_at);
CREATE INDEX ix_community_reports_target_status ON community_reports(target_type, target_id, status);
CREATE INDEX ix_moderation_cases_status ON moderation_cases(status, opened_at DESC);
CREATE INDEX ix_moderation_cases_target_user ON moderation_cases(target_user_id);
CREATE INDEX ix_admin_action_logs_admin_created ON admin_action_logs(admin_id, created_at DESC);
CREATE INDEX ix_admin_action_logs_target ON admin_action_logs(target_type, target_id);
CREATE INDEX ix_user_sanctions_user_status ON user_sanctions(user_id, status);
CREATE INDEX ix_ops_dashboard_snapshots_metric ON ops_dashboard_snapshots(metric_code, captured_at DESC);
CREATE INDEX ix_system_audit_logs_event_created ON system_audit_logs(event_type, created_at DESC);
